# OpenMC Native Installer (Patched for Windows)
# Generated by Antigravity
# Usage: .\install_openmc.ps1

Write-Host "Resuming OpenMC Build (Static Lib, No OpenMP, Standard C++)..." -ForegroundColor Cyan

# 1. Ensure Directory Exists
if (!(Test-Path "openmc/build")) {
    mkdir "openmc/build"
}

# 2. Configure (if not already done)
cd openmc/build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DOPENMC_USE_OPENMP=OFF -DCMAKE_CXX_FLAGS="/permissive- /std:c++17 /Zc:__cplusplus /EHsc /wd4244 /wd4267 /wd4297"

# 3. Build (Resume compilation)
Write-Host "Compiling... (This may take 10-20 minutes)" -ForegroundColor Yellow
cmake --build . --config Release --parallel 4

if ($LASTEXITCODE -ne 0) {
    Write-Error "Build Failed! Check logs."
    exit 1
}

# 4. Install Python Bindings
Write-Host "Build Complete! Installing Python bindings..." -ForegroundColor Green
cd ..
pip install .

Write-Host "OpenMC Installation Complete!" -ForegroundColor Green
python -c "import openmc; print('OpenMC Version:', openmc.__version__)"
